# Generated by Django 4.2.6 on 2023-11-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enikki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('enikki_id', models.CharField(max_length=100)),
                ('is_like', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user_id', 'enikki_id'), name='unique_like'),
        ),
    ]
