# Generated by Django 4.2.6 on 2023-11-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enikki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('img_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
