# Generated by Django 4.2.6 on 2023-10-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enikki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enikkimodel',
            name='group_name',
            field=models.CharField(default='group', max_length=100),
        ),
        migrations.AddField(
            model_name='enikkimodel',
            name='page_num',
            field=models.IntegerField(default=0),
        ),
    ]
