# Generated by Django 4.2.6 on 2024-02-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enikki', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequestTable',
        ),
    ]
