# Generated by Django 4.2.6 on 2023-11-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enikki', '0002_enikkimodel_group_name_enikkimodel_page_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('alt_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('enikki_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user_id', 'enikki_id'), name='unique_customer'),
        ),
    ]
