# Generated by Django 4.2.6 on 2023-11-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enikki', '0002_like_like_unique_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
