# Generated by Django 4.2.7 on 2023-11-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enikki', '0003_remove_like_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='enikkimodel',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
